##DIR_IA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/Oct17/sig_jobs_compCand_moriond17_IA_LeptonsMETBjets_v2/"
##DIR_OA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/Oct17/sig_jobs_compCand_moriond17_OA_LeptonsMETBjets_v2/"
##DIR_DATA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/Oct17/data_jobs_data_differential_afterMergeMusella_tightJetId_LeptonsMETjets_v2/"
#DIR_IA="root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/July_tightPuJetId/IA/"
#DIR_OA="root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/July_tightPuJetId/OA/"
#DIR_DATA="root://t3dcachedb.psi.ch:1094///pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/July_tightPuJetId/data/"

#SIGMODOPT="--skipCalcPhoSyst "
SIGMODOPT="--useFtest "
DATACARDOPT="--noSysts "


#bash reduceAndFit.sh --obs="Jet4p7AbsRapidity1" --ext="Jet4p7AbsRapidity1_tightJetPuId_test" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoJet4p7AbsRapidity1_m1000p0_0p0_SigmaMpTTag_1"  --refTagWV="recoJet4p7AbsRapidity1_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genJet4p7AbsRapidity1_m1000p0_0p0" --refProcDiff="InsideAcceptance_genJet4p7AbsRapidity1_m1000p0_0p0" --refProc="InsideAcceptance_genJet4p7AbsRapidity1_m1000p0_0p0" --skipSplit --sigModOpt="${SIGMODOPT}" ##"[1,-1.0,3.0]" 

5B
#bash reduceAndFit.sh --obs="NjetsBflavor4p7" --ext="NjetsBflavor4p7" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoNjetsBflavor4p7_m0p5_0p5_SigmaMpTTag_1"  --refTagWV="recoNjetsBflavor4p7_m0p5_0p5_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genNjetsBflavor4p7_m0p5_0p5" --refProcDiff="InsideAcceptance_genNjetsBflavor4p7_m0p5_0p5" --refProc="InsideAcceptance_genNjetsBflavor4p7_m0p5_0p5"  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" --skipSplit ##"[1,-1.0,3.0]" 


#bash reduceAndFit.sh --obs="NjetsBflavor4p7" --ext="NjetsBflavor4p7_newBins" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoNjetsBflavor4p7_m0p5_0p5_SigmaMpTTag_1"  --refTagWV="recoNjetsBflavor4p7_m0p5_0p5_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genNjetsBflavor4p7_m0p5_0p5" --refProcDiff="InsideAcceptance_genNjetsBflavor4p7_m0p5_0p5" --refProc="InsideAcceptance_genNjetsBflavor4p7_m0p5_0p5"  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" --skipSplit ##"[1,-1.0,3.0]" 


#bash reduceAndFit.sh --obs="Nleptons" --ext="Nleptons" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoNleptons_m0p5_0p5_SigmaMpTTag_1"  --refTagWV="recoNleptons_m0p5_0p5_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genNleptons_m0p5_0p5" --refProcDiff="InsideAcceptance_genNleptons_m0p5_0p5" --refProc="InsideAcceptance_genNleptons_m0p5_0p5"  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" --skipSplit ##"[1,-1.0,3.0]" 




#SIGMODOPT="--useFtest "
5B
#bash reduceAndFit.sh --obs="MET" --ext="MET_newBins_v2" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoMET_m0p5_100p0_SigmaMpTTag_1"  --refTagWV="recoMET_m0p5_100p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genMET_m0p5_100p0" --refProcDiff="InsideAcceptance_genMET_m0p5_100p0" --refProc="InsideAcceptance_genMET_m0p5_100p0"  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" --skipSplit ##"[1,-1.0,3.0]" 

#bash reduceAndFit.sh --obs="1LeptonHighMET" --ext="1LeptonHighMET" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="reco1LeptonHighMET_m1000p0_0p0_SigmaMpTTag_1"  --refTagWV="reco1LeptonHighMET_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_gen1LeptonHighMET_m1000p0_0p0" --refProcDiff="InsideAcceptance_gen1LeptonHighMET_m1000p0_0p0" --refProc="InsideAcceptance_gen1LeptonHighMET_m1000p0_0p0"  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##--skipSplit ##"[1,-1.0,3.0]" 

#bash reduceAndFit.sh --obs="1LeptonLowMET" --ext="1LeptonLowMET" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="reco1LeptonLowMET_m1000p0_0p0_SigmaMpTTag_1"  --refTagWV="reco1LeptonLowMET_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_gen1LeptonLowMET_m1000p0_0p0" --refProcDiff="InsideAcceptance_gen1LeptonLowMET_m1000p0_0p0" --refProc="InsideAcceptance_gen1LeptonLowMET_m1000p0_0p0"  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##--skipSplit ##"[1,-1.0,3.0]" 

#bash reduceAndFit.sh --obs="1Lepton1Bjet" --ext="1Lepton1Bjet" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="reco1Lepton1Bjet_m1000p0_0p0_SigmaMpTTag_1"  --refTagWV="reco1Lepton1Bjet_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_gen1Lepton1Bjet_m1000p0_0p0" --refProcDiff="InsideAcceptance_gen1Lepton1Bjet_m1000p0_0p0" --refProc="InsideAcceptance_gen1Lepton1Bjet_m1000p0_0p0"  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##--skipSplit ##"[1,-1.0,3.0]" 


#bash reduceAndFit.sh --obs="NjetsBflavorTight2p5" --ext="NjetsBflavorTight2p5" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoNjetsBflavorTight2p5_m0p5_0p5_SigmaMpTTag_1"  --refTagWV="recoNjetsBflavorTight2p5_m0p5_0p5_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genNjetsBflavorTight2p5_m0p5_0p5" --refProcDiff="InsideAcceptance_genNjetsBflavorTight2p5_m0p5_0p5" --refProc="InsideAcceptance_genNjetsBflavorTight2p5_m0p5_0p5"  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##--skipSplit ##"[1,-1.0,3.0]" 


#bash reduceAndFit.sh --obs="Pt" --ext="PtNNLOPS" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoPt_0p0_15p0_SigmaMpTTag_1"  --refTagWV="recoPt_0p0_15p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genPt_0p0_15p0" --refProcDiff="InsideAcceptance_genPt_0p0_15p0" --refProc="InsideAcceptance_genPt_0p0_15p0"  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ## --skipSplit   ##"[1,-1.0,3.0]" 

#bash reduceAndFit.sh --obs="Pt" --ext="Pt_Oct17_v2" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoPt_0p0_15p0_SigmaMpTTag_1"  --refTagWV="recoPt_0p0_15p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genPt_0p0_15p0" --refProcDiff="InsideAcceptance_genPt_0p0_15p0" --refProc="InsideAcceptance_genPt_0p0_15p0"  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##--skipSplit  ##"[1,-1.0,3.0]" 

#bash reduceAndFit.sh --obs="Njets2p5" --ext="Njets2p5" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoNjets2p5_m0p5_0p5_SigmaMpTTag_1"  --refTagWV="recoNjets2p5_m0p5_0p5_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genNjets2p5_m0p5_0p5" --refProcDiff="InsideAcceptance_genNjets2p5_m0p5_0p5" --refProc="InsideAcceptance_genNjets2p5_m0p5_0p5"  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" --skipSplit  ##"[1,-1.0,3.0]" 

#DIR_IA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/July_tightPuJetId/IA/"
#DIR_OA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/July_tightPuJetId/OA/"
#DIR_DATA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/July_tightPuJetId/data/"
#SIGMODOPT=""
#DATACARDOPT=""
#
#bash reduceAndFit.sh --obs="Pt" --ext="Pt" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoPt_0p0_15p0_SigmaMpTTag_1"  --refTagWV="recoPt_0p0_15p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genPt_0p0_15p0" --refProcDiff="InsideAcceptance_genPt_0p0_15p0" --refProc="InsideAcceptance_genPt_0p0_15p0" --skipSplit  ##--sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}"  ##"[1,-1.0,3.0]" 

DIR_IA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/Oct17/sig_jobs_compCand_moriond17_IA_withSysts_BjetsOnly/"
DIR_OA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/Oct17/sig_jobs_compCand_moriond17_OA_withSysts_BjetsOnly/"
SIGMODOPT="--useFtest "
#DATACARDOPT="--noSysts "
#bash reduceAndFit.sh --obs="Pt" --ext="PtNNLOPS_systs" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoPt_0p0_15p0_SigmaMpTTag_1"  --refTagWV="recoPt_0p0_15p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genPt_0p0_15p0" --refProcDiff="InsideAcceptance_genPt_0p0_15p0" --refProc="InsideAcceptance_genPt_0p0_15p0" ## --skipSplit ##  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 




DIR_IA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/Oct17/sig_jobs_compCand_moriond17_IA_withSysts_noBjets_v2/"
DIR_OA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/Oct17/sig_jobs_compCand_moriond17_OA_withSysts_noBjets_v2/"
DIR_DATA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/Oct17/data_jobs_data_differential_afterMergeMusella_tightJetId_LeptonsMETjets_v2/"
SIGMODOPT="--useFtest "

###bash reduceAndFit.sh --obs="Inclusive" --ext="InclusiveNNLOPS" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoInclusive_0p0_2p0_SigmaMpTTag_1"  --refTagWV="recoInclusive_0p0_2p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genInclusive_0p0_2p0" --refProcDiff="InsideAcceptance_genInclusive_0p0_2p0" --refProc="InsideAcceptance_genInclusive_0p0_2p0" ## --skipSplit ##  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
###bash reduceAndFit.sh --obs="Pt" --ext="PtNNLOPS_systs" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoPt_0p0_15p0_SigmaMpTTag_1"  --refTagWV="recoPt_0p0_15p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genPt_0p0_15p0" --refProcDiff="InsideAcceptance_genPt_0p0_15p0" --refProc="InsideAcceptance_genPt_0p0_15p0" ## --skipSplit ##  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="Njets2p5" --ext="Njets2p5NNLOPS" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoNjets2p5_m0p5_0p5_SigmaMpTTag_1"  --refTagWV="recoNjets2p5_m0p5_0p5_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genNjets2p5_m0p5_0p5" --refProcDiff="InsideAcceptance_genNjets2p5_m0p5_0p5" --refProc="InsideAcceptance_genNjets2p5_m0p5_0p5" ## --skipSplit ##  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##
##bash reduceAndFit.sh --obs="Jet2p5Pt0" --ext="Jet2p5Pt0NNLOPS" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoJet2p5Pt0_m1000p0_30p0_SigmaMpTTag_1"  --refTagWV="recoJet2p5Pt0_m1000p0_30p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genJet2p5Pt0_m1000p0_30p0" --refProcDiff="InsideAcceptance_genJet2p5Pt0_m1000p0_30p0" --refProc="InsideAcceptance_genJet2p5Pt0_m1000p0_30p0" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="Jet2p5AbsRapidity0" --ext="Jet2p5AbsRapidity0NNLOPS_newBins" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoJet2p5AbsRapidity0_0p5_1p2_SigmaMpTTag_1"  --refTagWV="recoJet2p5AbsRapidity0_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genJet2p5AbsRapidity0_m1000p0_0p0" --refProcDiff="InsideAcceptance_genJet2p5AbsRapidity0_0p5_1p2" --refProc="InsideAcceptance_genJet2p5AbsRapidity0_0p5_1p2" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="AbsDeltaPhiGgJet0Eta2p5_newBins" --ext="AbsDeltaPhiGgJet0Eta2p5NNLOPS_newBins" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoAbsDeltaPhiGgJet0Eta2p5_3p2_3p4_SigmaMpTTag_1"  --refTagWV="recoAbsDeltaPhiGgJet0Eta2p5_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genAbsDeltaPhiGgJet0Eta2p5_m1000p0_0p0" --refProcDiff="InsideAcceptance_genAbsDeltaPhiGgJet0Eta2p5_3p2_3p4" --refProc="InsideAcceptance_genAbsDeltaPhiGgJet0Eta2p5_3p2_3p4"  --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="AbsDeltaRapidityGgJet0Eta2p5" --ext="AbsDeltaRapidityGgJet0Eta2p5NNLOPS" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoAbsDeltaRapidityGgJet0Eta2p5_0p0_0p6_SigmaMpTTag_1"  --refTagWV="recoAbsDeltaRapidityGgJet0Eta2p5_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genAbsDeltaRapidityGgJet0Eta2p5_m1000p0_0p0" --refProcDiff="InsideAcceptance_genAbsDeltaRapidityGgJet0Eta2p5_0p0_0p6" --refProc="InsideAcceptance_genAbsDeltaRapidityGgJet0Eta2p5_0p0_0p6" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="Jet4p7Pt1" --ext="Jet4p7Pt1NNLOPS_tightJetPuId" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoJet4p7Pt1_45p0_90p0_SigmaMpTTag_1"  --refTagWV="recoJet4p7Pt1_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genJet4p7Pt1_m1000p0_0p0" --refProcDiff="InsideAcceptance_genJet4p7Pt1_45p0_90p0" --refProc="InsideAcceptance_genJet4p7Pt1_45p0_90p0" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="Jet4p7AbsRapidity1" --ext="Jet4p7AbsRapidity1NNLOPS_tightJetPuId" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoJet4p7AbsRapidity1_m1000p0_0p0_SigmaMpTTag_1"  --refTagWV="recoJet4p7AbsRapidity1_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genJet4p7AbsRapidity1_m1000p0_0p0" --refProcDiff="InsideAcceptance_genJet4p7AbsRapidity1_m1000p0_0p0" --refProc="InsideAcceptance_genJet4p7AbsRapidity1_m1000p0_0p0" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="AbsDeltaPhiJjEta4p7" --ext="AbsDeltaPhiJjEta4p7NNLOPS_tightJetPuId" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoAbsDeltaPhiJjEta4p7_0p9_1p8_SigmaMpTTag_1"  --refTagWV="recoAbsDeltaPhiJjEta4p7_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genAbsDeltaPhiJjEta4p7_m1000p0_0p0" --refProcDiff="InsideAcceptance_genAbsDeltaPhiJjEta4p7_0p9_1p8" --refProc="InsideAcceptance_genAbsDeltaPhiJjEta4p7_0p9_1p8" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="AbsDeltaPhiGgJjEta4p7" --ext="AbsDeltaPhiGgJjEta4p7NNLOPS_tightJetPuId" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoAbsDeltaPhiGgJjEta4p7_2p9_3p05_SigmaMpTTag_1"  --refTagWV="recoAbsDeltaPhiGgJjEta4p7_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genAbsDeltaPhiGgJjEta4p7_m1000p0_0p0" --refProcDiff="InsideAcceptance_genAbsDeltaPhiGgJjEta4p7_2p9_3p05" --refProc="InsideAcceptance_genAbsDeltaPhiGgJjEta4p7_2p9_3p05" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="ZeppenfeldEta4p7" --ext="ZeppenfeldEta4p7NNLOPS_tightJetPuId" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoZeppenfeldEta4p7_0p5_1p2_SigmaMpTTag_1"  --refTagWV="recoZeppenfeldEta4p7_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genZeppenfeldEta4p7y_m1000p0_0p0" --refProcDiff="InsideAcceptance_genZeppenfeldEta4p7y_0p5_1p2" --refProc="InsideAcceptance_genZeppenfeldEta4p7y_0p5_1p2" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="MjjEta4p7" --ext="MjjEta4p7NNLOPS_newBins_tightJetPuId" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoMjjEta4p7_150p0_450p0_SigmaMpTTag_1"  --refTagWV="recoMjjEta4p7_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genMjjEta4p7_m1000p0_0p0" --refProcDiff="InsideAcceptance_genMjjEta4p7_150p0_450p0" --refProc="InsideAcceptance_genMjjEta4p7_150p0_450p0" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="AbsDeltaEtaJJEta4p7" --ext="AbsDeltaEtaJJEta4p7NNLOPS_tightJetPuId" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoAbsDeltaEtaJJEta4p7_0p0_1p6_SigmaMpTTag_1"  --refTagWV="recoAbsDeltaEtaJJEta4p7_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genAbsDeltaEtaJJEta4p7_m1000p0_0p0" --refProcDiff="InsideAcceptance_genAbsDeltaEtaJJEta4p7_0p0_1p6" --refProc="InsideAcceptance_genAbsDeltaEtaJJEta4p7_0p0_1p6" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="Jet4p7Pt1VBFlike" --ext="Jet4p7Pt1VBFlikeNNLOPS_tightJetPuId" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoJet4p7Pt1VBFlike_45p0_90p0_SigmaMpTTag_1"  --refTagWV="recoJet4p7Pt1VBFlike_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genJet4p7Pt1VBFlike_m1000p0_0p0" --refProcDiff="InsideAcceptance_genJet4p7Pt1VBFlike_45p0_90p0" --refProc="InsideAcceptance_genJet4p7Pt1VBFlike_45p0_90p0" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="AbsDeltaPhiJjEta4p7VBFlike" --ext="AbsDeltaPhiJjEta4p7VBFlikeNNLOPS_tightJetPuId" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoAbsDeltaPhiJjEta4p7VBFlike_0p9_1p8_SigmaMpTTag_1"  --refTagWV="recoAbsDeltaPhiJjEta4p7VBFlike_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genAbsDeltaPhiJjEta4p7VBFlike_m1000p0_0p0" --refProcDiff="InsideAcceptance_genAbsDeltaPhiJjEta4p7VBFlike_0p9_1p8" --refProc="InsideAcceptance_genAbsDeltaPhiJjEta4p7VBFlike_0p9_1p8" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="AbsDeltaPhiGgJjEta4p7VBFlike" --ext="AbsDeltaPhiGgJjEta4p7VBFlikeNNLOPS_tightJetPuId" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoAbsDeltaPhiGgJjEta4p7VBFlike_2p9_3p05_SigmaMpTTag_1"  --refTagWV="recoAbsDeltaPhiGgJjEta4p7VBFlike_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genAbsDeltaPhiGgJjEta4p7VBFlike_m1000p0_0p0" --refProcDiff="InsideAcceptance_genAbsDeltaPhiGgJjEta4p7VBFlike_2p9_3p05" --refProc="InsideAcceptance_genAbsDeltaPhiGgJjEta4p7VBFlike_2p9_3p05" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 
##
##bash reduceAndFit.sh --obs="PtNjets2p5" --ext="PtNjets2p5NNLOPS_newBins" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoPtNjets2p5_13000p0_13060p0_SigmaMpTTag_1"  --refTagWV="recoPtNjets2p5_0p0_20p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genPtNjets2p5_0p0_20p0" --refProcDiff="InsideAcceptance_genPtNjets2p5_13000p0_13060p0" --refProc="InsideAcceptance_genPtNjets2p5_13000p0_13060p0" --sigModOpt="${SIGMODOPT}" ## --skipSplit ##   --DatacardOpt="${DATACARDOPT}" ##    ##"[1,-1.0,3.0]" 

DIR_IA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/Oct17/sig_jobs_compCand_moriond17_IA_withSysts_BjetsOnly/"
DIR_OA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/Oct17/sig_jobs_compCand_moriond17_OA_withSysts_BjetsOnly/"
DIR_DATA="root://t3dcachedb.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/vtavolar/Differentials_ntuples/Oct17/data_jobs_data_differential_afterMergeMusella_tightJetId_LeptonsMETjets_v2/"

bash reduceAndFit.sh --obs="Pt" --ext="PtNNLOPS_newBins" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoPt_0p0_15p0_SigmaMpTTag_1"  --refTagWV="recoPt_0p0_15p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genPt_0p0_15p0" --refProcDiff="InsideAcceptance_genPt_0p0_15p0" --refProc="InsideAcceptance_genPt_0p0_15p0" --skipSplit --runCombineOnly=1 --range="1,0.0,3.0" --npoints=30 --runSignalOnly=0 --runBackgroundOnly=0 --unblind=1 ##  --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##    ##"1,-1.0,3.0" 

reduceAndFit.sh --obs="AbsRapidity" --ext="AbsRapidityNNLOPS_newBins_combination" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoAbsRapidity_0p3_0p6_SigmaMpTTag_1"  --refTagWV="recoAbsRapidity_0p3_0p6_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genAbsRapidity_0p3_0p6" --refProcDiff="InsideAcceptance_genAbsRapidity_0p3_0p6" --refProc="InsideAcceptance_genAbsRapidity_0p3_0p6" --skipSplit --runCombineOnly=1 --range="1,-1.0,3.0" --npoints=20 --runSignalOnly=0 --runBackgroundOnly=0 --unblind=1 ##--sigModOpt="${SIGMODOPT}" ##  ## ##   --DatacardOpt="${DATACARDOPT}" ##    ##"1,-1.0,3.0" 

bash reduceAndFit.sh --obs="AbsRapidity" --ext="AbsRapidityNNLOPS_newBins" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoAbsRapidity_0p3_0p6_SigmaMpTTag_1"  --refTagWV="recoAbsRapidity_0p3_0p6_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genAbsRapidity_0p3_0p6" --refProcDiff="InsideAcceptance_genAbsRapidity_0p3_0p6" --refProc="InsideAcceptance_genAbsRapidity_0p3_0p6" --sigModOpt="${SIGMODOPT}" --skipSplit --runDatacardOnly=0 --range="1,0.3,1.7" --npoints=20 --shiftOffDiag=0  --runSignalOnly=0 --runBackgroundOnly=0 --runCombineOnly=1 --unblind=1 ## ##   --DatacardOpt="${DATACARDOPT}" ##    ##"1,-1.0,3.0" 

bash reduceAndFit.sh --obs="CosThetaStar" --ext="CosThetaStarNNLOPS" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoCosThetaStar_0p1_0p25_SigmaMpTTag_1"  --refTagWV="recoCosThetaStar_0p1_0p25_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genCosThetaStar_0p1_0p25" --refProcDiff="InsideAcceptance_genCosThetaStar_0p1_0p25" --refProc="InsideAcceptance_genCosThetaStar_0p1_0p25" --sigModOpt="${SIGMODOPT}" --skipSplit --runDatacardOnly=0 --range="1,0.3,1.7" --npoints=20 --shiftOffDiag=0  --runSignalOnly=0 --runBackgroundOnly=0 --runCombineOnly=1 --unblind=1 ## ##  --DatacardOpt="${DATACARDOPT}" ##    ##"1,-1.0,3.0" 

bash reduceAndFit.sh --obs="MET" --ext="METNNLOPS_newBins_v2" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoMET_m0p5_100p0_SigmaMpTTag_1"  --refTagWV="recoMET_m0p5_100p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genMET_m0p5_100p0" --refProcDiff="InsideAcceptance_genMET_m0p5_100p0" --refProc="InsideAcceptance_genMET_m0p5_100p0"  --noSkip  --sigModOpt="${SIGMODOPT}" --skipSplit --runDatacardOnly=0 --range="1,-2.5,4.5" --npoints=50   --shiftOffDiag=0  --runSignalOnly=0 --runBackgroundOnly=0 --runCombineOnly=1 --unblind=1 ### --DatacardOpt="${DATACARDOPT}"  ##"1,-1.0,3.0" 

bash reduceAndFit.sh --obs="NjetsBflavorTight2p5" --ext="NjetsBflavorTight2p5NNLOPS" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoNjetsBflavorTight2p5_m0p5_0p5_SigmaMpTTag_1"  --refTagWV="recoNjetsBflavorTight2p5_m0p5_0p5_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genNjetsBflavorTight2p5_m0p5_0p5" --refProcDiff="InsideAcceptance_genNjetsBflavorTight2p5_m0p5_0p5" --refProc="InsideAcceptance_genNjetsBflavorTight2p5_m0p5_0p5"  --noSkip  --sigModOpt="${SIGMODOPT}" --skipSplit --runCombineOnly=1 --range="1,-3.0,5.0" --npoints=70  --shiftOffDiag=0 --runSignalOnly=0 --runBackgroundOnly=0 --unblind=1 ###--DatacardOpt="${DATACARDOPT}" ## ##"1,-1.0,3.0" 

bash reduceAndFit.sh --obs="Nleptons" --ext="NleptonsNNLOPS" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoNleptons_m0p5_0p5_SigmaMpTTag_1"  --refTagWV="recoNleptons_m0p5_0p5_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genNleptons_m0p5_0p5" --refProcDiff="InsideAcceptance_genNleptons_m0p5_0p5" --refProc="InsideAcceptance_genNleptons_m0p5_0p5"   --noSkip  --sigModOpt="${SIGMODOPT}" --skipSplit --runCombineOnly=1 --range="1,-3.5,5.5" --npoints=70 --shiftOffDiag=0 --runSignalOnly=0 --runBackgroundOnly=0 --unblind=1 ### --DatacardOpt="${DATACARDOPT}"  ##"1,-1.0,3.0" 

bash reduceAndFit.sh --obs="1LeptonHighMET" --ext="1LeptonHighMETNNLOPS" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="reco1LeptonHighMET_m1000p0_0p0_SigmaMpTTag_1"  --refTagWV="reco1LeptonHighMET_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_gen1LeptonHighMET_m1000p0_0p0" --refProcDiff="InsideAcceptance_gen1LeptonHighMET_m1000p0_0p0" --refProc="InsideAcceptance_gen1LeptonHighMET_m1000p0_0p0" --noSkip --sigModOpt="${SIGMODOPT}" --skipSplit --runDatacardOnly=0 --range="1,-2.5,4.5" --npoints=50 --shiftOffDiag=0 --runSignalOnly=0 --runBackgroundOnly=0 --runCombineOnly=1 --unblind=1 #--DatacardOpt="${DATACARDOPT}" ## ##"1,-1.0,3.0" 

bash reduceAndFit.sh --obs="1LeptonLowMET" --ext="1LeptonLowMETNNLOPS" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="reco1LeptonLowMET_m1000p0_0p0_SigmaMpTTag_1"  --refTagWV="reco1LeptonLowMET_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_gen1LeptonLowMET_m1000p0_0p0" --refProcDiff="InsideAcceptance_gen1LeptonLowMET_m1000p0_0p0" --refProc="InsideAcceptance_gen1LeptonLowMET_m1000p0_0p0" --noSkip  --sigModOpt="${SIGMODOPT}" --skipSplit --runDatacardOnly=0 --range="1,-2.5,4.5" --npoints=50 --shiftOffDiag=0 --runSignalOnly=0 --runBackgroundOnly=0 --runCombineOnly=1 --unblind=1 ## --DatacardOpt="${DATACARDOPT}" ## ##"1,-1.0,3.0"

bash reduceAndFit.sh --obs="1Lepton1Bjet" --ext="1Lepton1BjetNNLOPS" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="reco1Lepton1Bjet_m1000p0_0p0_SigmaMpTTag_1"  --refTagWV="reco1Lepton1Bjet_m1000p0_0p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_gen1Lepton1Bjet_m1000p0_0p0" --refProcDiff="InsideAcceptance_gen1Lepton1Bjet_m1000p0_0p0" --refProc="InsideAcceptance_gen1Lepton1Bjet_m1000p0_0p0" --noSkip --sigModOpt="${SIGMODOPT}" --runDatacardOnly=0 --range="1,0,5.5" --npoints=35  --shiftOffDiag=0 --runSignalOnly=0 --runBackgroundOnly=0 --runCombineOnly=1 --unblind=1 --skipSplit ##--skipSplit --DatacardOpt="${DATACARDOPT}" ## ##"1,-1.0,3.0" 


##BOOSTED HIGGS
##bash reduceAndFit.sh --obs="Pt" --ext="PtNNLOPS_boosted" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoPt_0p0_450p0_SigmaMpTTag_1"  --refTagWV="recoPt_0p0_450p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genPt_0p0_450p0" --refProcDiff="InsideAcceptance_genPt_0p0_450p0" --refProc="InsideAcceptance_genPt_0p0_450p0"  --runCombineOnly=1 --range="1,-1.0,3.0" --npoints=40 --skipSplit ##   --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##    ##"1,-1.0,3.0" 
##bash reduceAndFit.sh --obs="Pt" --ext="PtNNLOPS_boosted_v2" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoPt_0p0_350p0_SigmaMpTTag_1"  --refTagWV="recoPt_0p0_350p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genPt_0p0_350p0" --refProcDiff="InsideAcceptance_genPt_0p0_350p0" --refProc="InsideAcceptance_genPt_0p0_350p0"  --runCombineOnly=0 --range="1,-1.0,3.0" --npoints=40  --skipSplit ##   --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##    ##"1,-1.0,3.0" 

##bash reduceAndFit.sh --obs="Pt" --ext="PtNNLOPS_boosted600_v2" --dirIA=${DIR_IA} --dirOA=${DIR_OA} --dirData=${DIR_DATA} --refTagDiff="recoPt_0p0_350p0_SigmaMpTTag_1"  --refTagWV="recoPt_0p0_350p0_SigmaMpTTag_1"  --refProcWV="InsideAcceptance_genPt_0p0_350p0" --refProcDiff="InsideAcceptance_genPt_0p0_350p0" --refProc="InsideAcceptance_genPt_0p0_350p0"  --runCombineOnly=1 --range="1,-1.0,5.0" --npoints=60  --skipSplit ##   --sigModOpt="${SIGMODOPT}" --DatacardOpt="${DATACARDOPT}" ##    ##"1,-1.0,3.0" 
